### PR TITLE
Update some upstream repos to ensure juju/mgo is used everywhere

### PR DESCRIPTION
**Pull request by wallyworld**
This PR is basically import churn to bring in new upstream repo versions:
- gopkg.in/macaroon-bakery.v3
- github.com/jujusimplekv
- github.com/juju/utils/v2

These upstream changes ensure github.com/juju/mgo/v2 is used in place of gopkg.in/mgo.v2
The juju version is maintained and has additional bug fixes.
This is part of an effort to migrate to juju/mgo across the board.

The module version has been bumped to v2.

### CODE REVIEW

**Review by mhilton — CHANGES_REQUESTED** [review]
This changes the signatures on candidclient methods and therefore isn't backwards compatible. Please increment the module version so we don't break existing clients.

**Comment by wallyworld** [comment]
> This changes the signatures on candidclient methods and therefore isn't backwards compatible. Please increment the module version so we don't break existing clients.

Done.
We'll need to remember create a v0 branch off the current master before merging this.

**Review by mhilton — CHANGES_REQUESTED** [review]
I really don't want to move this module into gopkg.in.

**Comment by wallyworld** [comment]
Since the changes to pull out macaroon serialisation from macaroon-bakery, we can avoid this change for now.

**Pull request closed without merging**
