### PR TITLE
Update SSO buttons

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Update the IDP login buttons according to designs

## QA
- Make sure you have all dependencies:
  - `snap install go`
  - `sudo apt install build-essential bzr git`
- Delete the contents of `cmd/candidsrv/config.yaml` and paste in https://pastebin.canonical.com/p/59WVqnRjbT/
- Run the site `make server`
- Go to http://localhost:8081/login
- Check that there is one SSO button that spans the width of the container
- Delete the contents of `cmd/candidsrv/config.yaml` and paste in https://pastebin.canonical.com/p/nDNZk5dkTW/
- Check that there are two SSO buttons and are equal sizes
- Delete the contents of `cmd/candidsrv/config.yaml` and paste in https://pastebin.canonical.com/p/zpFVfQh6PK/
- Check that there are three SSO buttons and fill the whole width in a row
- Delete the contents of `cmd/candidsrv/config.yaml` and paste in https://pastebin.canonical.com/p/sf5VgDZgmn/
- Check that there are four SSO buttons and they wrap after three

## Issue
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1839

## Screenshots
Mobile:
mobile

One button:
one_button

Two buttons:
two_buttons

Three buttons:
three_buttons

Four buttons:
four_buttons

### CODE REVIEW

**Review by mhilton — APPROVED** [review]
seems fine to me

**Review by tbille — APPROVED** [review]
LGTM

**Comment by steverydz** [comment]
@mhilton everyone's happy for this to be merged on our side

**Comment by mhilton** [comment]
> @mhilton everyone's happy for this to be merged on our side

Thanks very much

**Pull request merged**
